[package]

name = "secp256k1"
version = "0.12.2"
authors = [ "Dawid Ciężarkiewicz <dpc@ucore.info>",
            "Andrew Poelstra <apoelstra@wpsoftware.net>" ]
license = "CC0-1.0"
homepage = "https://github.com/rust-bitcoin/rust-secp256k1/"
repository = "https://github.com/rust-bitcoin/rust-secp256k1/"
documentation = "https://docs.rs/secp256k1/"
description = "Rust bindings for Pieter Wuille's `libsecp256k1` library. Implements ECDSA for the SECG elliptic curve group secp256k1 and related utilities."
keywords = [ "crypto", "ECDSA", "secp256k1", "libsecp256k1", "bitcoin" ]
readme = "README.md"
build = "build.rs"

# Should make docs.rs show all functions, even those behind non-default features
[package.metadata.docs.rs]
features = [ "rand", "serde" ]
all-features = true

[build-dependencies]
cc = "=1.0.35"

[lib]
name = "secp256k1"
path = "src/lib.rs"

[features]
unstable = []
default = []
fuzztarget = []

[dev-dependencies]
rand = "0.6"
rand_core = "0.3"
serde_test = "1.0"

[dependencies.rand]
version = "0.6"
optional = true

[dependencies.serde]
version = "1.0"
optional = true
